#ifndef __COMMON_H__
#define __COMMON_H__

#define EXIPRE_TIME_SECONDS_2DAYS (2 * 24 * 3600)
#define EXIPRE_TIME_SECONDS_7DAYS (7 * 24 * 3600)
#define OTAI_VS_SYNCD_TTL_PM_15MIN "OTAI_VS_SYNCD_TTL_PM_15MIN"
#define OTAI_VS_SYNCD_TTL_PM_24HOUR "OTAI_VS_SYNCD_TTL_PM_24HOUR"
#define OTAI_VS_SYNCD_TTL_ALARM "OTAI_VS_SYNCD_TTL_ALARM"

#endif