#ifndef __COMMON_H__
#define __COMMON_H__

#define EXIPRE_TIME_SECONDS_2DAYS (2 * 24 * 3600)
#define EXIPRE_TIME_SECONDS_7DAYS (7 * 24 * 3600)
#define LAI_VS_SYNCD_TTL_PM_15MIN "LAI_VS_SYNCD_TTL_PM_15MIN"
#define LAI_VS_SYNCD_TTL_PM_24HOUR "LAI_VS_SYNCD_TTL_PM_24HOUR"
#define LAI_VS_SYNCD_TTL_ALARM "LAI_VS_SYNCD_TTL_ALARM"

#endif