#!/bin/sh
set -e
# Automatically added by dh_installinit/13.3.3~bpo10+1
if [ -x "/etc/init.d/syncd" ] && [ "$1" = remove ]; then
	invoke-rc.d syncd stop || exit 1
fi
# End automatically added section
